# Generated by Django 4.2.2 on 2023-06-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Idolo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotografia', models.ImageField(upload_to='ejecutivos')),
                ('rut', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Ejecutivo',
        ),
    ]
