# Generated by Django 4.2.3 on 2023-07-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Idolo', '0002_idolo_delete_ejecutivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idolo',
            name='fotografia',
            field=models.ImageField(upload_to='idolos'),
        ),
    ]
